"""update field is_provider table

Revision ID: 586198893d89
Revises: 2f2c4f135723
Create Date: 2022-09-28 20:47:17.927476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586198893d89'
down_revision = '62837285e8fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
