"""actualizando columna de name en location y warehouse

Revision ID: 76c16cf14fd9
Revises: 9fd74e18eaf8
Create Date: 2022-11-11 00:05:57.382964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c16cf14fd9'
down_revision = '9fd74e18eaf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_location_name'), 'location', ['name'], unique=True, schema='stock')
    op.create_index(op.f('ix_stock_warehouse_name'), 'warehouse', ['name'], unique=True, schema='stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_warehouse_name'), table_name='warehouse', schema='stock')
    op.drop_index(op.f('ix_stock_location_name'), table_name='location', schema='stock')
    # ### end Alembic commands ###
