"""add field status_name in contract table

Revision ID: 868ea237fb33
Revises: 4b5bfded6a56
Create Date: 2022-12-23 08:23:35.805608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868ea237fb33'
down_revision = '4b5bfded6a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('status_name', sa.String(length=50), nullable=True), schema='contract')
    op.create_foreign_key(None, 'contracts', 'status_element', ['status_name'], ['name'], source_schema='contract', referent_schema='resources')
    op.alter_column('users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='enterprise')
    op.alter_column('users', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='enterprise')
    op.alter_column('partners', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='partner')
    op.alter_column('users', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='enterprise')
    op.alter_column('users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='enterprise')
    op.drop_constraint(None, 'contracts', schema='contract', type_='foreignkey')
    op.drop_column('contracts', 'status_name', schema='contract')
    # ### end Alembic commands ###
