"""modify partner table

Revision ID: a7eb018101b0
Revises: 76c16cf14fd9
Create Date: 2022-11-22 13:04:35.618846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7eb018101b0'
down_revision = '76c16cf14fd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('products',
    # sa.Column('id', sa.String(), nullable=False),
    # sa.Column('code', sa.String(length=24), nullable=False),
    # sa.Column('name', sa.String(length=250), nullable=False),
    # sa.Column('description', sa.String(length=200), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('measurement', sa.String(), nullable=False),
    # sa.Column('unit_price', sa.Float(), nullable=False),
    # sa.Column('cost_price', sa.Float(), nullable=True),
    # sa.Column('sale_price', sa.Float(), nullable=True),
    # sa.Column('ledger_account', sa.String(length=250), nullable=True),
    # sa.Column('created_by', sa.String(length=50), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=False),
    # sa.Column('updated_by', sa.String(length=50), nullable=False),
    # sa.Column('updated_date', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='stock'
    # )
    # op.create_table('warehouse',
    # sa.Column('id', sa.String(), nullable=False),
    # sa.Column('name', sa.String(length=250), nullable=False),
    # sa.Column('address', sa.String(length=400), nullable=True),
    # sa.Column('code', sa.String(length=30), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('created_by', sa.String(length=50), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=False),
    # sa.Column('updated_by', sa.String(length=50), nullable=False),
    # sa.Column('updated_date', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='stock'
    # )
    # op.create_index(op.f('ix_stock_warehouse_name'), 'warehouse', ['name'], unique=True, schema='stock')
    # op.create_table('location',
    # sa.Column('id', sa.String(), nullable=False),
    # sa.Column('name', sa.String(length=250), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('corridor', sa.Integer(), nullable=True),
    # sa.Column('floor', sa.Integer(), nullable=True),
    # sa.Column('observation', sa.String(length=500), nullable=True),
    # sa.Column('created_by', sa.String(length=50), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=False),
    # sa.Column('updated_by', sa.String(length=50), nullable=False),
    # sa.Column('updated_date', sa.DateTime(), nullable=False),
    # sa.Column('warehouse_id', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['warehouse_id'], ['stock.warehouse.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='stock'
    # )
    # op.create_index(op.f('ix_stock_location_name'), 'location', ['name'], unique=True, schema='stock')
    # op.create_table('movements',
    # sa.Column('id', sa.String(), nullable=False),
    # sa.Column('product_id', sa.String(), nullable=False),
    # sa.Column('quantity', sa.Integer(), nullable=False),
    # sa.Column('status_id', sa.Integer(), nullable=False),
    # sa.Column('source', sa.String(), nullable=False),
    # sa.Column('destiny', sa.String(), nullable=False),
    # sa.Column('measurement', sa.String(), nullable=True),
    # sa.Column('document_number', sa.String(length=100), nullable=True),
    # sa.Column('created_by', sa.String(length=50), nullable=False),
    # sa.Column('created_date', sa.DateTime(), nullable=False),
    # sa.Column('updated_by', sa.String(length=50), nullable=False),
    # sa.Column('updated_date', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['destiny'], ['stock.location.id'], ),
    # sa.ForeignKeyConstraint(['product_id'], ['stock.products.id'], ),
    # sa.ForeignKeyConstraint(['source'], ['stock.location.id'], ),
    # sa.ForeignKeyConstraint(['status_id'], ['resources.status_element.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='stock'
    # )
    op.add_column('partners', sa.Column('registration_number', sa.Integer(), nullable=True), schema='partner')
    op.add_column('partners', sa.Column('registration_user', sa.String(length=350), nullable=True), schema='partner')
    op.add_column('partners', sa.Column('registration_date', sa.Date(), nullable=True), schema='partner')
    op.add_column('partners', sa.Column('type', sa.String(length=60), nullable=False), schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'type', schema='partner')
    op.drop_column('partners', 'registration_date', schema='partner')
    op.drop_column('partners', 'registration_user', schema='partner')
    op.drop_column('partners', 'registration_number', schema='partner')
    op.drop_table('movements', schema='stock')
    op.drop_index(op.f('ix_stock_location_name'), table_name='location', schema='stock')
    op.drop_table('location', schema='stock')
    op.drop_index(op.f('ix_stock_warehouse_name'), table_name='warehouse', schema='stock')
    op.drop_table('warehouse', schema='stock')
    op.drop_table('products', schema='stock')
    # ### end Alembic commands ###
