"""creando codificador measure

Revision ID: aef0ac579a04
Revises: 296bdc06e03a
Create Date: 2022-11-30 15:40:42.509561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef0ac579a04'
down_revision = '296bdc06e03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_index(op.f('ix_stock_measure_name'), 'measure', ['name'], unique=True, schema='stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_measure_name'), table_name='measure', schema='stock')
    op.drop_table('measure', schema='stock')
    # ### end Alembic commands ###
