"""add contacts table

Revision ID: e21bd7b93238
Revises: ccc93a091ef8
Create Date: 2022-11-25 09:10:50.042834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21bd7b93238'
down_revision = 'ccc93a091ef8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('dni', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('mobile', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='partner'
    )
    op.create_table('partners_contacts',
    sa.Column('id_partner', sa.String(), nullable=False),
    sa.Column('id_contact', sa.String(), nullable=False),
    sa.Column('id_relationtype', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_contact'], ['partner.contacts.id'], ),
    sa.ForeignKeyConstraint(['id_partner'], ['partner.partners.id'], ),
    sa.ForeignKeyConstraint(['id_relationtype'], ['partner.relationtype.id'], ),
    sa.PrimaryKeyConstraint('id_partner', 'id_contact'),
    schema='partner'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partners_contacts', schema='partner')
    op.drop_table('contacts', schema='partner')
    # ### end Alembic commands ###
