"""add invoices table

Revision ID: 0477154e6a82
Revises: 8c4e270b5bc0
Create Date: 2022-09-28 21:59:48.260215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0477154e6a82'
down_revision = '2f2c4f135723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_import', sa.Float(), nullable=True),
    sa.Column('real_import', sa.Float(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('observation', sa.String(length=350), nullable=False),
    sa.Column('status', sa.String(length=35), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='invoice'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices', schema='invoice')
    # ### end Alembic commands ###
