"""add mark table

Revision ID: 8d317bd9e900
Revises: 52ec6b38254b
Create Date: 2023-07-17 22:15:12.224602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d317bd9e900'
down_revision = '52ec6b38254b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='stock'
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_table('products_marks',
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mark_id'], ['stock.marks.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['stock.products.id'], ),
    sa.PrimaryKeyConstraint('mark_id', 'product_id'),
    schema='stock'
    )
    op.add_column('products', sa.Column('classification_id', sa.Integer(), nullable=True), schema='stock')
    
#     op.create_foreign_key(
#     "fk_prod_clasification",
#     "stock.classification",
#     "stock.products",
#     ["id"],
#     ["classification_id"],
# )
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_marks', schema='stock')
    op.drop_table('marks', schema='stock')
    op.drop_table('classification', schema='stock')
    # ### end Alembic commands ###
