"""add mark table

Revision ID: 8d317bd9e900
Revises: 52ec6b38254b
Create Date: 2023-07-17 22:15:12.224602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d317bd9e901'
down_revision = '8d317bd9e900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
#     op.create_foreign_key(
#     "fk_prod_clasification",
#     "stock.classification",
#     "stock.products",
#     ["id"],
#     ["classification_id"],
# )
    
    op.create_foreign_key(
    "fk_prod_clasification",
    "stock.products",
    "stock.classification",
    ["classification_id"],
    ["id"],
)
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
