"""Added schema stock with entity warehouse, localtio, product, movement

Revision ID: 9fd74e18eaf8
Revises: bcf490ffa5ba
Create Date: 2022-11-06 13:55:40.703116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fd74e18eaf8'
down_revision = 'bcf490ffa5ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('measurement', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('ledger_account', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_table('warehouse',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_table('location',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('corridor', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('observation', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['stock.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_table('movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('destiny', sa.String(), nullable=False),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destiny'], ['stock.location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['stock.products.id'], ),
    sa.ForeignKeyConstraint(['source'], ['stock.location.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.status_element.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.drop_table('info_cxc', schema='cxc')
    op.drop_table('contracts', schema='info_contracts')
    op.drop_table('fac_talonnumeracion', schema='versat')
    op.drop_table('fac_pfestado', schema='versat')
    op.drop_table('fac_numeracion', schema='versat')
    op.drop_table('fac_formapago', schema='versat')
    op.drop_table('fac_talonestado', schema='versat')
    op.drop_table('gen_entidad', schema='versat')
    op.drop_table('fac_talonnumberprefolio', schema='versat')
    op.drop_table('cierre', schema='info_cxc')
    op.drop_table('fac_talonfoliocancelados', schema='versat')
    op.drop_table('fac_detallebs', schema='versat')
    op.drop_table('fac_numerocons', schema='versat')
    op.drop_table('fac_talonformato', schema='versat')
    op.drop_table('fac_talonprefactura', schema='versat')
    op.drop_table('fac_talon', schema='versat')
    op.drop_table('fac_factura', schema='versat')
    op.drop_table('fac_talonfactura', schema='versat')
    op.drop_table('fac_canceladas', schema='versat')
    op.drop_table('fac_estadodoc', schema='versat')
    op.drop_table('fac_talonfolio', schema='versat')
    op.drop_table('fac_talontipo', schema='versat')
    op.drop_table('fac_tipoforma', schema='versat')
    op.drop_table('fac_talonregistro', schema='versat')
    op.drop_table('fac_talonfoliodist', schema='versat')
    op.alter_column('partners', 'is_provider',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='partner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partners', 'is_provider',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='partner')
    op.create_table('fac_talonfoliodist',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pagina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_talonregistro',
    sa.Column('idregistrotalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idunidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numinicial', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numerofinal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtipofactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_tipoforma',
    sa.Column('idtipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_talontipo',
    sa.Column('idtipotalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_talonfolio',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_estadodoc',
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_canceladas',
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('nota', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('idtipo', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_talonfactura',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_factura',
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idunidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idusuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('porcarancel', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('imparancelmn', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('imparancelmlc', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('observacion', sa.VARCHAR(length=2005), autoincrement=False, nullable=True),
    sa.Column('idcontratovta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('importemn', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('importemlc', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('idconceptooblig', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idperiodo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctabcomn', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ctabcomlc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idempresa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precioest', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('idforma', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idunidademitida', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numcons', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('resumen', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('confirmo', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('termino', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('creaoblig', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('idoperacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idregistrotalon', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vtacadena', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('creadescuento', postgresql.BIT(length=1), autoincrement=False, nullable=True),
    sa.Column('crearetencion', postgresql.BIT(length=1), autoincrement=False, nullable=True),
    sa.Column('crc', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chkcontrol', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('chkdate', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('factelect', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_talon',
    sa.Column('idtalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('idformato', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posicion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charbefore', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charafter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtipotalon', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_talonprefactura',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idprefactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtalonnumerofact', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_talonformato',
    sa.Column('idregistro', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posicion', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('longitud', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_numerocons',
    sa.Column('idunidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtipofactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numcons', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_detallebs',
    sa.Column('iddetalle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idctocontrap', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idmedida', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('cantidadeq', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('preciomn', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('preciomlc', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('porcrecdesc', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('volrecdesc', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('importerecdescmn', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('importerecdescmlc', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('preciovtamn', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('preciovtamlc', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('importemn', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('importemlc', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('importemnc', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
    sa.Column('importemlcc', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('porcrecdescom', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('volrecdescom', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('precioiden', sa.NUMERIC(precision=18, scale=7), autoincrement=False, nullable=True),
    sa.Column('crc', sa.BIGINT(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_talonfoliocancelados',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('observacion', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('idusuario', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('cierre',
    sa.Column('No_PREFACTURA', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('2022', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('column3', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column4', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column5', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column6', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column7', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column8', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column9', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column10', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column11', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column12', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('column13', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('column14', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='info_cxc'
    )
    op.create_table('fac_talonnumberprefolio',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idregistrotalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('enuso', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('gen_entidad',
    sa.Column('identidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('codigoreu', sa.VARCHAR(length=19), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('abreviatura', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('activo', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ircc', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_talonestado',
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_formapago',
    sa.Column('idformapago', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forma', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('idtipo', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_numeracion',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idfactura', sa.INTEGER(), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('fac_pfestado',
    sa.Column('idestado', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='versat'
    )
    op.create_table('fac_talonnumeracion',
    sa.Column('idtalonnumero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idregistrotalon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('enuso', postgresql.BIT(length=1), autoincrement=False, nullable=False),
    schema='versat'
    )
    op.create_table('contracts',
    sa.Column('no_contract', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_operation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    schema='info_contracts'
    )
    op.create_table('info_cxc',
    sa.Column('no_prefacture', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_genesi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_collage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_isa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_way', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_offer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_invoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('column4', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    schema='cxc'
    )
    op.drop_table('movements', schema='stock')
    op.drop_table('location', schema='stock')
    op.drop_table('warehouse', schema='stock')
    op.drop_table('products', schema='stock')
    # ### end Alembic commands ###
