"""add job field to contacts table

Revision ID: ea2be5e0c9ac
Revises: dfd26e8b86c4
Create Date: 2022-12-19 03:16:14.828062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2be5e0c9ac'
down_revision = 'dfd26e8b86c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='stock'
    )
    op.create_index(op.f('ix_stock_measure_name'), 'measure', ['name'], unique=True, schema='stock')
    op.alter_column('users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='enterprise')
    op.alter_column('users', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='enterprise')
    op.add_column('contacts', sa.Column('job', sa.String(length=50), nullable=True), schema='partner')
    op.alter_column('partners', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='partner')
    op.add_column('movements', sa.Column('measure_id', sa.Integer(), nullable=False), schema='stock')
    op.create_foreign_key(None, 'movements', 'measure', ['measure_id'], ['id'], source_schema='stock', referent_schema='stock')
    op.drop_column('movements', 'measurement', schema='stock')
    op.add_column('products', sa.Column('measure_id', sa.Integer(), nullable=False), schema='stock')
    op.create_foreign_key(None, 'products', 'measure', ['measure_id'], ['id'], source_schema='stock', referent_schema='stock')
    op.drop_column('products', 'measurement', schema='stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('measurement', sa.VARCHAR(), autoincrement=False, nullable=False), schema='stock')
    op.drop_constraint(None, 'products', schema='stock', type_='foreignkey')
    op.drop_column('products', 'measure_id', schema='stock')
    op.add_column('movements', sa.Column('measurement', sa.VARCHAR(), autoincrement=False, nullable=True), schema='stock')
    op.drop_constraint(None, 'movements', schema='stock', type_='foreignkey')
    op.drop_column('movements', 'measure_id', schema='stock')
    op.alter_column('partners', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='partner')
    op.drop_column('contacts', 'job', schema='partner')
    op.alter_column('users', 'selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='enterprise')
    op.alter_column('users', 'job',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='enterprise')
    op.drop_index(op.f('ix_stock_measure_name'), table_name='measure', schema='stock')
    op.drop_table('measure', schema='stock')
    # ### end Alembic commands ###
